workflows:
  android-release:
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Clean project
        script: cd android && ./gradlew clean
      - name: Build release APK
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - rlrahim74@gmail.com
