workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      vars:
        ANDROID_HOME: $ANDROID_SDK_ROOT
    scripts:
      - name: Set Gradle wrapper permissions
        script: chmod +x ./gradlew
      - name: Clean project
        script: ./gradlew clean
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
