workflows:
  android-release:
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: "11"
      groups:
        - keystore_credentials   # <- we'll store keys here in Codemagic UI
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - rlrahim74@gmail.com
