workflows:
  android-release:
    name: Build Android release
    environment:
      java: 17
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
